# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 1048576);
user_pref("browser.migration.version", 5);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.startup.homepage", "www.telestany.com");
user_pref("browser.startup.homepage_override.buildID", "20110622232052");
user_pref("browser.startup.homepage_override.mstone", "rv:5.0");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 3);
user_pref("extensions.enabledAddons", "langpack-en-ZA@firefox.mozilla.org:5.0,langpack-ca@firefox.mozilla.org:5.0,globalmenu@ubuntu.com:1.0.6,langpack-en-GB@firefox.mozilla.org:5.0,ubufox@ubuntu.com:0.9.1,{972ce4c6-7e08-4474-a285-3208198ce6fd}:5.0");
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1309155882000}}},{\"name\":\"app-global\",\"addons\":{\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-5.0/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1308798200000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox-5.0/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1309155826000},\"langpack-ca@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-5.0/extensions/langpack-ca@firefox.mozilla.org.xpi\",\"mtime\":1308798198000},\"globalmenu@ubuntu.com\":{\"descriptor\":\"/usr/lib/firefox-5.0/extensions/globalmenu@ubuntu.com\",\"mtime\":1309155822000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-5.0/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1308798199000}}}]");
user_pref("extensions.lastAppVersion", "5.0");
user_pref("extensions.pendingOperations", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 47074);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1313307149);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
user_pref("network.proxy.http", "127.0.0.1");
user_pref("network.proxy.http_port", 8118);
user_pref("network.proxy.type", 1);

